version: '3.2'
services:

  #Postgres Service
  postgres:
    image: postgres:latest
    container_name: postgres_cart
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "7001:5432"
      - "443:443"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e_cart
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ecommerce_cart
      SERVICE_TAGS: dev
    working_dir: /opt/cart
    ports:
      - 7000:3000
    volumes:
      - ./:/opt/cart
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
